name: JsonTest
on:
  workflow_dispatch:
    inputs:
        app:
          type: choice
          description: Select a component to deploy
          options:
          - -Select-
          - search-api
          - request-api
          required: true
      
jobs:
  build-push-image-searchapi:
    name: build-push-image-searchapi
    runs-on: ubuntu-latest
    env: 
      app: ${{github.event.inputs.app}}
    steps:
      - name: Checkoutcode
        uses: actions/checkout@v2
        with:
          path: .
      
      - name: Fetch Project Path
        id: fetch_projectpath
        env:
          APP: ${{ env.app }}
        run: >-
          echo "::set-output name=PATH::$(
            jq .ProjectMapping.\"${APP}\" ./test.json
          )"
      
      - name: print env variables
        env:
          PROJECT_PATH: "${{ steps.fetch_projectpath.outputs.PATH }}"
        run: |
          echo "Release Environment: Dev"
          echo "Release App: ${{ env.app }}"
          echo "Project Path: ${PROJECT_PATH}"
