name: BuildPushSearchAPIToDEV
on:
  workflow_dispatch:
    inputs:
        app:
          type: choice
          description: Select a component to deploy
          options:
          - -Select-
          - search-api
          required: true
        env:
            description: 'Image Target Env'     
            required: true
            default: 'dev'
        imagename:
            description: 'Imagename to deploy'     
            required: true
            default: 'search-api-expt'
        tag:
            description: 'Target image tag to build and deploy'     
            required: true
            default: 'exptag'
        startup_project:
            description: 'Project for Dotnet Core MSBuild ''   
            required: true
            default: 'SearchApi/SearchApi.Web/SearchApi.Web.csproj'
      
jobs:
  build-push-image-searchapi:
    name: build-push-image-searchapi
    runs-on: ubuntu-latest
    env: 
      env: ${{github.event.inputs.env}}
      app: ${{github.event.inputs.app}}
      imagename: ${{github.event.inputs.imagename}}
      tag: ${{github.event.inputs.tag}}
      startup_project: ${{github.event.inputs.startup_project}}
    steps:
      - name: Checkoutcode
        uses: actions/checkout@v2
        with:
          path: .

      - name: print env variables
        run: |
          echo "Release Environment: ${{ env.env }}"
          echo "Release App: ${{ env.app }}"

      - name: Login to OpenShift Container Repository
        uses: docker/login-action@v1
        with:
          registry: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY}}
          username: ssuganth77
          password: sha256~RqecbRJ97AmtKenINr-1cg0gDDFVrUFsyWNTXq7rFg4
      
      - name: Pull Image from OpenShift Container Repository
        env:
          IMAGE: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY}}/${{secrets.OPENSHIFT_TOOLS_NAMESPACE}}/dotnet31-rhel7:sdk-custom
        run: docker pull ${IMAGE}

      - name: Build Image using S2I
        id: build_image
        uses: redhat-actions/s2i-build@v2
        with:
            path_context: ./app
            builder_image:  ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY}}/${{secrets.OPENSHIFT_TOOLS_NAMESPACE}}/dotnet31-rhel7:sdk-custom
            image: ${{ env.imagename}}
            tags: ${{ env.tag }}
            env_vars: |
              DOTNET_STARTUP_PROJECT=SearchApi/SearchApi.Web/SearchApi.Web.csproj    
              DOTNET_CONFIGURATION=Release
              DOTNET_PACK=true
              WORKDIR=/opt/app-root/src
              DOTNET_INCREMENTAL=true
              DOTNET_RESTORE_CONFIGFILE=./NuGet.config
              NEXUS_REPO_USER=${{ secrets.NEXUS_REPO_USER }}
              NEXUS_REPO_PASSWORD=${{ secrets.NEXUS_REPO_PASSWORD }}
              NEXUS_REPO_URL=${{secrets.NEXUS_URL}}
      
      - name: Push Image to Openshift ImageStream & Deploy to Dev
        env:
          IMAGE: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY}}/${{secrets.OPENSHIFT_TOOLS_NAMESPACE}}/${{ env.imagename}}:${{ env.tag }}
        run: docker push ${IMAGE}
